const types = {
    ADDRESS_LOAD: 'ADDRESS_LOAD',
    ADDRESS_LOAD_SUCCESS: 'ADDRESS_LOAD_SUCCESS',
    ADDRESS_LOAD_FAIL: 'ADDRESS_LOAD_FAIL',
    FETCH_COORDINATES: 'FETCH_COORDINATES',
    FETCH_COORDINATES_SUCCESS: 'FETCH_COORDINATES_SUCCESS',
    FETCH_COORDINATES_FAIL: 'FETC_COORDINATES_FAIL',
};

export default types;